# Generated by Django 5.1.5 on 2025-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variationproduit",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
