# Generated by Django 5.1.5 on 2025-03-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_alter_table_and_Promotion_table_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={},
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix',
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.BooleanField(default=True),
        ),
    ]
