# Generated by Django 5.1.5 on 2025-04-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ecommerce", "0002_variationproduit_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variationproduit",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
