# Generated by Django 5.1.5 on 2025-03-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0003_alter_promotion_options_remove_produit_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationproduit',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
