# Generated by Django 5.1.5 on 2025-03-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_remove_produit_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variationproduit',
            name='quantite',
            field=models.IntegerField(help_text='Quantité disponible'),
        ),
    ]
