# Generated by Django 5.1.5 on 2025-04-09 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ecommerce", "0006_remove_adresse_code_postal_adresse_nom_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mode",
            options={
                "verbose_name": "Mode de paiement",
                "verbose_name_plural": "Modes de paiement",
            },
        ),
        migrations.AddField(
            model_name="mode",
            name="code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="mode",
            name="expiration",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="mode",
            name="numero",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mode",
            name="numero_tel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mode",
            name="type_paiement",
            field=models.CharField(
                choices=[
                    ("MOBILE_MONEY", "Mobile Money"),
                    ("CREDIT_CARD", "Carte de crédit/débit"),
                    ("PREPAID_CARD", "Carte prépayée"),
                ],
                default="MOBILE_MONEY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mode",
            name="utilisateur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mode",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
