# Generated by Django 5.1.5 on 2025-03-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0006_produit_stock_alter_variationproduit_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut_paiement',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EFFECTUEE', 'Effectué')], max_length=50, null=True),
        ),
    ]
