# Generated by Django 5.1.5 on 2025-04-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ecommerce", "0007_alter_mode_options_mode_code_mode_expiration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livraison",
            name="adresse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Ecommerce.adresse",
            ),
        ),
    ]
