# Generated by Django 5.1.5 on 2025-03-20 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0007_paiement_est_actif_paiement_statut_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='variationproduit',
            name='images',
            field=models.ImageField(null=True, upload_to='Variant_produit'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='produits',
            field=models.ManyToManyField(to='Ecommerce.variationproduit'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Panier_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
