# Generated by Django 5.1.5 on 2025-03-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0008_variationproduit_images_alter_panier_produits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationproduit',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
