# Generated by Django 5.1.5 on 2025-03-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0009_variationproduit_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoris',
            name='produit',
        ),
        migrations.AddField(
            model_name='favoris',
            name='produit',
            field=models.ManyToManyField(to='Ecommerce.variationproduit'),
        ),
    ]
