# Generated by Django 5.1.5 on 2025-03-22 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0010_remove_favoris_produit_favoris_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut_commande',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EXPEDIEE', 'Expédiée'), ('ANNULEE', 'Annulée')], max_length=50),
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.produit')),
            ],
            options={
                'unique_together': {('commande', 'produit')},
            },
        ),
    ]
