# Generated by Django 5.1.5 on 2025-03-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0011_alter_commande_statut_commande_commandeproduit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produits',
        ),
    ]
