# Generated by Django 5.1.5 on 2025-04-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0011_commune_frais_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='frais_livraison',
            field=models.FloatField(null=True),
        ),
    ]
