# Generated by Django 5.1.5 on 2025-03-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0012_remove_commande_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeproduit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commandeproduit',
            name='est_actif',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='commandeproduit',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commande_Produit_ids', to='Ecommerce.commande'),
        ),
        migrations.AlterField(
            model_name='commandeproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.variationproduit'),
        ),
    ]
