# Generated by Django 5.1.5 on 2025-03-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0013_commandeproduit_created_at_commandeproduit_est_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeproduit',
            name='prix',
            field=models.FloatField(null=True),
        ),
    ]
