# Generated by Django 5.1.5 on 2025-04-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ecommerce", "0013_commande_prix_total_alter_commande_prix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="prix",
            field=models.FloatField(null=True),
        ),
    ]
