# Generated by Django 5.1.5 on 2025-04-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0014_commandeproduit_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(default=False, help_text='Indique si la promotion est active'),
        ),
    ]
