# Generated by Django 5.1.5 on 2025-04-11 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ecommerce", "0015_commande_mode_alter_commande_statut_commande_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="paiement",
        ),
        migrations.AddField(
            model_name="paiement",
            name="commande",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paiements",
                to="Ecommerce.commande",
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="commande",
            name="statut_commande",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("CONFIRMEE", "Confirmée"),
                    ("ANNULEE", "Annulée"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mode",
            name="type_paiement",
            field=models.CharField(
                choices=[
                    ("MOBILE_MONEY", "Mobile Money"),
                    ("CREDIT_CARD", "Carte de crédit/débit"),
                    ("PREPAID_CARD", "Carte prépayée"),
                    ("LIQUIDE", "Liquide"),
                ],
                default="Mobile Money",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="statut_paiement",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("EFFECTUE", "Effectué"),
                    ("ECHOUE", "Echoué"),
                ],
                default="EN_ATTENTE",
                max_length=50,
            ),
        ),
    ]
