# Generated by Django 5.1.5 on 2025-04-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0015_alter_promotion_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieproduit',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
