# Generated by Django 5.1.5 on 2025-04-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0016_remove_commande_paiement_paiement_commande_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
