# Generated by Django 5.1.5 on 2025-04-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0016_categorieproduit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieproduit',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
