# Generated by Django 5.1.5 on 2025-04-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ecommerce", "0018_remove_paiement_est_actif_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avis",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Ecommerce.variationproduit",
            ),
        ),
    ]
