# Generated by Django 5.1.5 on 2025-10-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0019_alter_avis_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoris',
            name='produit',
            field=models.ManyToManyField(related_name='Favoris_ids', to='Ecommerce.variationproduit'),
        ),
    ]
