# Generated by Django 5.1.5 on 2025-11-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0004_activationotp'),
        ('Ecommerce', '0020_alter_favoris_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='Authentification.vendeur'),
        ),
    ]
