# Generated by Django 5.1.5 on 2025-11-02 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentification", "0004_activationotp"),
        ("Ecommerce", "0021_produit_vendeur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="statut_commande",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("CONFIRMEE", "Confirmée"),
                    ("TERMINEE", "Terminée"),
                    ("ANNULEE", "Annulée"),
                ],
                default="En attente",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SellerCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("ACCEPTEE", "Acceptée"),
                            ("REFUSEE", "Refusée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sellercommandes",
                        to="Ecommerce.commande",
                    ),
                ),
                (
                    "vendeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_commandes",
                        to="Authentification.vendeur",
                    ),
                ),
            ],
            options={
                "unique_together": {("commande", "vendeur")},
            },
        ),
    ]
