# Generated by Django 5.1.5 on 2025-11-02 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentification", "0005_livreur"),
        ("Ecommerce", "0022_alter_commande_statut_commande_sellercommande"),
    ]

    operations = [
        migrations.AddField(
            model_name="livraison",
            name="assigned_courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="livraisons",
                to="Authentification.livreur",
            ),
        ),
        migrations.AddField(
            model_name="livraison",
            name="code_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="livraison",
            name="delivery_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name="LivraisonTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("EN_COURS", "En cours"),
                            ("EXPEDIEE", "Expédiée"),
                            ("LIVREE", "Livrée"),
                            ("RETOURNEE", "Retournée"),
                        ],
                        max_length=50,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("actor", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "livraison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="Ecommerce.livraison",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
