# Generated by Django 5.1.5 on 2025-11-02 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentification", "0005_livreur"),
        ("Ecommerce", "0023_livraison_assigned_courier_livraison_code_used_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="vendeur",
        ),
        migrations.AddField(
            model_name="variationproduit",
            name="vendeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variations",
                to="Authentification.vendeur",
            ),
        ),
    ]
