# Generated by Django 5.1.5 on 2025-11-03 00:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentification", "0005_livreur"),
    ]

    operations = [
        migrations.AddField(
            model_name="livreur",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livreur",
            name="last_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
