# Generated by Django 5.1.5 on 2025-03-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_date_de_publicatio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_de_publicatio',
            field=models.DateField(auto_now=True, verbose_name='Date de publication'),
        ),
    ]
